### ISSUE TITLE
Docs for Ruby packages

### ISSUE THREAD

**Issue by Coding-Cactus** [DillonB07/Whoosh#7]
- [ ] bundler
- [ ] rails
- [ ] devise
- [ ] minitest
- [ ] rspec
- [ ] sinatra
- [ ] sidekiq
- [ ] pg
- [ ] sqlite3
- [ ] mongo
- [ ] rubocop
- [ ] http
- [ ] json
- [ ] discordrb
- [ ] nokogiri
- [ ] faker
- [ ] bcrypt

**Comment by DillonB07** [comment]
Closing as this will be unnecessary due to new implementation in #9
